### ISSUE TITLE
[Feat] API 호출을 통한 사고 변환 결과 화면 기능 구현

### ISSUE THREAD

**Issue by jane1choi** [jane1choi/LuckyVicky#33]
## 🍀 Feature Issue
- API 호출을 통해 사고 변환 결과를 보여줄 수 있도록 기능을 구현합니다.

## 📝 To-do
- [x] 뷰모델에서 api 호출
- [x] 캐릭터 별 SystemContent 추가
- [x] 결과 화면 표시
- [x] 네트워크 에러 처리
