### ISSUE TITLE
[Refactor] 네트워크 통신 로직 리팩토링

### ISSUE THREAD

**Issue by jane1choi** [jane1choi/LuckyVicky#46]
## 🍀 Feature Issue
Service <- Repository <- UseCase <- ViewModel 의 일관된 흐름으로 네트워크 통신이 이루어질 수 있도록 코드를 리팩토링합니다.

## 📝 To-do
- [x] firebase를 이용한 통신에도 service 객체 두기
- [x] repository, usecase 역할 명확히 분리
- [x] usecase에 viewModel의 로직을 덜어낼 수 있도록 코드 개선
