### ISSUE TITLE
[Feat] 스플래시 뷰 UI 구성 및 초기 화면 전환 구현

### ISSUE THREAD

**Issue by jane1choi** [jane1choi/LuckyVicky#8]
## 🍀 Feature Issue
- 스플래시 뷰의 UI를 구현합니다.

## 📝 To-do
- [x] 앱 아이콘 추가
- [x] 스플래시 뷰 UI 구현
- [x] 초기 화면 전환 구현
- [x] 앱 diplay name 설정
